// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/search-venues.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_venues_default = defineTool({
  name: "search_venues",
  title: "Search venues",
  description: "Search Bites venues in Buenos Aires by keyword (name/description), cuisine, neighborhood, tag, price range, minimum rating, or open-now. Returns compact venue rows.",
  inputSchema: {
    query: z.string().trim().optional().describe("Free-text keyword matched against name and description."),
    cuisine: z.string().trim().optional(),
    neighborhood: z.string().trim().optional(),
    tag: z.string().trim().optional(),
    max_price: z.number().int().min(1).max(4).optional(),
    min_rating: z.number().min(0).max(5).optional(),
    open_now: z.boolean().optional(),
    limit: z.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    const limit = input.limit ?? 20;
    let q = sb(ctx).from("venues").select("id,slug,name,description,cuisine,neighborhood,rating,review_count,price_range,is_open,tags,address,image_url").eq("status", "approved").order("rating", { ascending: false }).limit(limit);
    if (input.query) q = q.or(`name.ilike.%${input.query}%,description.ilike.%${input.query}%`);
    if (input.cuisine) q = q.ilike("cuisine", `%${input.cuisine}%`);
    if (input.neighborhood) q = q.ilike("neighborhood", `%${input.neighborhood}%`);
    if (input.tag) q = q.contains("tags", [input.tag]);
    if (input.max_price) q = q.lte("price_range", input.max_price);
    if (input.min_rating) q = q.gte("rating", input.min_rating);
    if (input.open_now) q = q.eq("is_open", true);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Found ${data?.length ?? 0} venues.` }],
      structuredContent: { venues: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-venue.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_venue_default = defineTool2({
  name: "get_venue",
  title: "Get venue details",
  description: "Fetch full venue details (plus recent reviews) by venue id or slug.",
  inputSchema: {
    id: z2.string().trim().optional(),
    slug: z2.string().trim().optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, slug }, ctx) => {
    if (!id && !slug) return { content: [{ type: "text", text: "Provide id or slug." }], isError: true };
    const client = sb2(ctx);
    let query = client.from("venues").select("*").eq("status", "approved").limit(1);
    query = id ? query.eq("id", id) : query.eq("slug", slug);
    const { data: venues, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const venue = venues?.[0];
    if (!venue) return { content: [{ type: "text", text: "Venue not found." }], isError: true };
    const { data: reviews } = await client.from("venue_reviews").select("rating,content,created_at,user_id").eq("venue_id", venue.id).order("created_at", { ascending: false }).limit(10);
    return {
      content: [{ type: "text", text: `${venue.name} \u2014 ${venue.neighborhood} \xB7 ${venue.cuisine} \xB7 \u2605${venue.rating}` }],
      structuredContent: { venue, reviews: reviews ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-neighborhoods.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_neighborhoods_default = defineTool3({
  name: "list_neighborhoods",
  title: "List neighborhoods",
  description: "Return the list of neighborhoods with venue counts.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const { data, error } = await sb3(ctx).from("venues").select("neighborhood").eq("status", "approved");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const counts = /* @__PURE__ */ new Map();
    for (const row of data ?? []) counts.set(row.neighborhood, (counts.get(row.neighborhood) ?? 0) + 1);
    const neighborhoods = [...counts.entries()].map(([name, count]) => ({ name, count })).sort((a, b) => b.count - a.count);
    return {
      content: [{ type: "text", text: `${neighborhoods.length} neighborhoods.` }],
      structuredContent: { neighborhoods }
    };
  }
});

// src/lib/mcp/tools/list-favorites.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_favorites_default = defineTool4({
  name: "list_my_favorites",
  title: "List my favorites",
  description: "List venues favorited by the signed-in user.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    const { data, error } = await sb4(ctx).from("favorites").select("venue_id,created_at,venues(id,slug,name,neighborhood,cuisine,rating,image_url)").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `${data?.length ?? 0} favorites.` }],
      structuredContent: { favorites: data ?? [] }
    };
  }
});
var addFavoriteTool = defineTool4({
  name: "add_favorite",
  title: "Add favorite",
  description: "Mark a venue as favorite for the signed-in user.",
  inputSchema: { venue_id: z3.string().uuid() },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ venue_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    const { error } = await sb4(ctx).from("favorites").upsert({ user_id: ctx.getUserId(), venue_id });
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: "Favorited." }] };
  }
});
var removeFavoriteTool = defineTool4({
  name: "remove_favorite",
  title: "Remove favorite",
  description: "Remove a venue from the signed-in user's favorites.",
  inputSchema: { venue_id: z3.string().uuid() },
  annotations: { readOnlyHint: false, idempotentHint: true, destructiveHint: true, openWorldHint: false },
  handler: async ({ venue_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    const { error } = await sb4(ctx).from("favorites").delete().eq("user_id", ctx.getUserId()).eq("venue_id", venue_id);
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: "Removed." }] };
  }
});

// src/lib/mcp/tools/lists.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
function sb5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var listMyListsTool = defineTool5({
  name: "list_my_lists",
  title: "List my lists",
  description: "List the signed-in user's curated venue lists.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    const { data, error } = await sb5(ctx).from("lists").select("id,name,description,is_public,cover_image_url,created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: `${data?.length ?? 0} lists.` }], structuredContent: { lists: data ?? [] } };
  }
});
var createListTool = defineTool5({
  name: "create_list",
  title: "Create list",
  description: "Create a new venue list for the signed-in user.",
  inputSchema: {
    name: z4.string().trim().min(1).max(120),
    description: z4.string().trim().max(500).optional(),
    is_public: z4.boolean().optional()
  },
  annotations: { readOnlyHint: false, openWorldHint: false },
  handler: async ({ name, description, is_public }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    const { data, error } = await sb5(ctx).from("lists").insert({ user_id: ctx.getUserId(), name, description: description ?? null, is_public: is_public ?? false }).select().single();
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: `Created list "${data.name}".` }], structuredContent: { list: data } };
  }
});
var addVenueToListTool = defineTool5({
  name: "add_venue_to_list",
  title: "Add venue to list",
  description: "Add a venue to one of the signed-in user's lists.",
  inputSchema: {
    list_id: z4.string().uuid(),
    venue_id: z4.string().uuid(),
    note: z4.string().trim().max(500).optional()
  },
  annotations: { readOnlyHint: false, openWorldHint: false },
  handler: async ({ list_id, venue_id, note }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    const { error } = await sb5(ctx).from("list_items").insert({ list_id, venue_id, note: note ?? null });
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: "Added." }] };
  }
});

// src/lib/mcp/tools/checkins.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^3.25.76";
function sb6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var listCheckinsTool = defineTool6({
  name: "list_my_checkins",
  title: "List my check-ins",
  description: "Return the signed-in user's most recent venue check-ins.",
  inputSchema: { limit: z5.number().int().min(1).max(50).optional() },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    const { data, error } = await sb6(ctx).from("check_ins").select("id,note,rating,created_at,venues(id,name,neighborhood,cuisine)").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: `${data?.length ?? 0} check-ins.` }], structuredContent: { check_ins: data ?? [] } };
  }
});
var createCheckinTool = defineTool6({
  name: "create_checkin",
  title: "Create check-in",
  description: "Record that the signed-in user visited a venue. Optional short note and 1-5 rating.",
  inputSchema: {
    venue_id: z5.string().uuid(),
    note: z5.string().trim().max(500).optional(),
    rating: z5.number().int().min(1).max(5).optional()
  },
  annotations: { readOnlyHint: false, openWorldHint: false },
  handler: async ({ venue_id, note, rating }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    const { error } = await sb6(ctx).from("check_ins").insert({ user_id: ctx.getUserId(), venue_id, note: note ?? null, rating: rating ?? null });
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: "Checked in." }] };
  }
});

// src/lib/mcp/tools/create-review.ts
import { createClient as createClient7 } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z6 } from "npm:zod@^3.25.76";
function sb7(ctx) {
  return createClient7(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_review_default = defineTool7({
  name: "create_review",
  title: "Create review",
  description: "Post a review for a venue as the signed-in user (rating 1-5 and text).",
  inputSchema: {
    venue_id: z6.string().uuid(),
    rating: z6.number().int().min(1).max(5),
    content: z6.string().trim().min(1).max(2e3)
  },
  annotations: { readOnlyHint: false, openWorldHint: false },
  handler: async ({ venue_id, rating, content }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    const { data, error } = await sb7(ctx).from("venue_reviews").insert({ user_id: ctx.getUserId(), venue_id, rating, content }).select().single();
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : { content: [{ type: "text", text: "Review posted." }], structuredContent: { review: data } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hbzokqnpridsccyhdony";
var mcp_default = defineMcp({
  name: "bites-mcp",
  title: "Bites \u2014 Buenos Aires gastro",
  version: "0.1.0",
  instructions: "Tools for Bites, a Buenos Aires restaurant discovery app. Search and read public venue data, and \u2014 as the signed-in user \u2014 manage favorites, lists, check-ins and reviews.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_venues_default,
    get_venue_default,
    list_neighborhoods_default,
    list_favorites_default,
    addFavoriteTool,
    removeFavoriteTool,
    listMyListsTool,
    createListTool,
    addVenueToListTool,
    listCheckinsTool,
    createCheckinTool,
    create_review_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
